[settings]
# Публичные API-данные Telegram Desktop. Рекомендую изменить (https://my.telegram.org/apps/)
api_id = 2040
api_hash = b18441a1ff607e10a989891a5462e627

# Сколько сообщений удалять за один запрос
batch = 100

# Пауза между запросами в секундах
delay = 1.2

[whitelist]
# Источники сообщений, которые необходимо пропустить.
# Формат: username без @ или числовой ID, через запятую. Пример: durov, -1001234567890
chats =

[message_whitelist]
# Конкретные сообщения, которые необходимо пропустить. Форматы через запятую:
# https://t.me/username/123, https://t.me/c/1234567890/123, chat_id:message_id
messages =